### ISSUE TITLE
"Fill with Random Data"

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/fraud-detection-example#3]
Could you add a "Fill with Random Data" button that fills all the fields with some data? Maybe we could create 3-5 sets of sample data that get filled in?

Happy to create the sample data, just let me know what format it should be in.

**Comment by walkah** [comment]
@mattfogel how do you want to select random locations? just have a set of 5-10 and pick from those?

**Comment by mattfogel** [comment]
Yeah, I was thinking something like:

Ex1: New York, New York, New York
Ex2: San Francisco, New York, New York
Ex3: New York, Beijing, New York
etc..

With a few different variations on distance between the locations.
