### ISSUE TITLE
Agent: Price difference

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/fraud-detection-example#5]
If I understand the agent correctly, I think there may be an issue with how price difference is set up. Our ideal situation is one where we have very little difference in price, so 0 price difference should mean a very low likelihood of fraud.

As things are set up now, a 0 there gives a medium likelihood of fraud.

What I propose doing is calculating the price difference and using the absolute number only, and setting that input up to range from 0 to 100

**Comment by walkah** [comment]
Ah, yeah, I was thinking that only things way over avg price ... but is it just distance from avg price? That's an easy change.

**Comment by mattfogel** [comment]
Hmm actually that's a really good point. I guess in this case the issue really is with anything being greater than average price and not distance from average price. In that case 0-100 should still be the range, and then a negative different in price is as good as 0 difference in price. Make sense?

**Comment by walkah** [comment]
Got it!
