### ISSUE TITLE
Issue calculating distances?

### ISSUE THREAD

**Issue by mattfogel** [fuzzy-ai/fraud-detection-example#9]
I just ran a test where billing address is in SF, shipping address is Beijing, IP address is New York and phone is in Beijing.

Here are the inputs that were submitted:

`{"userAgeInDays":6,"shippingDistance":0,"IPDistance":11001.401784985712,"phoneDistance":0,"priceDifference":0,"shippingOption":1,"numberPreviousFromIP":15,"numberPreviousShipping":14}`

shippingDistance and phoneDistance are both 0, but should be much larger.

**Comment by walkah** [comment]
typo in random generation
